.PHONY: all clean
all:
	@$(MAKE) -C DeprecationManager
	@$(MAKE) -C FreeImage
	@$(MAKE) -C FreeImageToolkit
	@$(MAKE) -C Metadata

clean:
	@$(MAKE) -C DeprecationManager clean
	@$(MAKE) -C FreeImage clean
	@$(MAKE) -C FreeImageToolkit clean
	@$(MAKE) -C Metadata clean
